name: lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12
    - uses: pnpm/action-setup@v1.2.0
      with:
        version: 5
        run_install: true
    - run: pnpm run lint
